# Generated by Django 5.1.1 on 2025-09-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Package_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='current_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='from_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='to_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('shipped', 'Shipped'), ('in_transit', 'In Transit'), ('customs_clearance', 'Customs Clearance'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered')], default='processing', max_length=20),
        ),
    ]
